
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-oldmonk-remotegarage-club-v1-queueautoscaler
  failurePolicy: Fail
  name: mqueueautoscaler.kb.io
  rules:
  - apiGroups:
    - oldmonk.remotegarage.club
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - queueautoscalers

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-oldmonk-remotegarage-club-v1-queueautoscaler
  failurePolicy: Fail
  name: vqueueautoscaler.kb.io
  rules:
  - apiGroups:
    - oldmonk.remotegarage.club
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - queueautoscalers
