apiVersion: v1
kind: Secret
metadata:
  name: queue-config
type: Opaque
data:
  URI: "aHR0cHM6Ly9zcXMuYXAtc291dGgtMS5hbWF6b25hd3MuY29tLzEzMTIyMDIzNzA3MS90ZXN0Cg=="
---
apiVersion: oldmonk.evalsocket.in/v1
kind: QueueAutoScaler
metadata:
  name: lifecycle
spec:
  type: "SQS"
  policy: "THRESOLD"
  option:
    region: 'ap-south-1'
  secrets: queue-config
  maxPods: 4
  minPods: 1
  scaleDown:
    amount: 1
    threshold: 3
  scaleUp:
    amount: 1
    threshold: 4
  deployment: 'nginx'
  labels:
    env: dev
    app: nginx
  autopilot: false