apiVersion: v1
kind: Secret
metadata:
  name: queue-config
type: Opaque
data:
  URI: "aHR0cHM6Ly9zcXMuYXAtc291dGgtMS5hbWF6b25hd3MuY29tLzEzMTIyMDIzNzA3MS90ZXN0Cg=="
---
apiVersion: oldmonk.evalsocket.in/v1
kind: QueueAutoScaler
metadata:
  name: lifecycle
spec:
  type: "SQS"
  policy: "TARGET"
  targetMessagesPerWorker: 1
  option:
    region: 'ap-south-1'
  secrets: queue-config
  maxPods: 10
  minPods: 0
  scaleDown:
    amount: 1
    threshold: 1
  scaleUp:
    amount: 1
    threshold: 4
  deployment: 'nginx'
  labels:
    env: dev
    app: nginx
  autopilot: true
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  appSpec:
    name: 'nginx-deployment'
    image: "nginx:latest"
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: queue-config